// app/og/[...slug]/route.tsx — Dynamic Open Graph image generator
// Generates custom OG images for each page/locale at runtime
// Uses @vercel/og (Edge-compatible, free on Vercel)

import { ImageResponse } from 'next/og'
import { NextRequest }   from 'next/server'

export const runtime = 'edge'

const BASE = process.env.NEXT_PUBLIC_APP_URL ?? 'https://msctutor.in'

// Page metadata for OG images
const PAGE_DATA: Record<string, { title: string; subtitle: string; icon: string; color: string }> = {
  home:       { title:'MscTutor', subtitle:'Free AI Tutor for Class 1-12 NCERT', icon:'🎓', color:'#1a3a6b' },
  ask:        { title:'Ask AI — Free!', subtitle:'Text • Image • Voice • PDF — Any subject, any class', icon:'🤖', color:'#2563eb' },
  'ai-teacher':{ title:'AI Teacher', subtitle:'Adaptive learning that remembers your progress', icon:'👩‍🏫', color:'#059669' },
  formulas:   { title:'Formula Bank', subtitle:'1000+ NCERT Formulas — Class 6 to 12', icon:'📐', color:'#7c3aed' },
  'mock-test':{ title:'AI Mock Test', subtitle:'Board exam practice generated by AI', icon:'📋', color:'#dc2626' },
  class:      { title:'NCERT Classes', subtitle:'Class 1-12 • All Subjects • Free AI Solutions', icon:'📚', color:'#0369a1' },
  community:  { title:'Community', subtitle:'Learn together with students across India', icon:'🌍', color:'#065f46' },
  pricing:    { title:'Pricing', subtitle:'Free for all students. Premium for power users.', icon:'💎', color:'#d97706' },
  blog:       { title:'Education Blog', subtitle:'Study tips, NCERT help & learning strategies', icon:'✍️', color:'#374151' },
}

// Locale labels for OG image
const LOCALE_LABELS: Record<string, string> = {
  en:'English', hi:'हिंदी', bn:'বাংলা', gu:'ગુજરાતી', mr:'मराठी',
  ta:'தமிழ்', te:'తెలుగు', pa:'ਪੰਜਾਬੀ', ur:'اردو', as:'অসমীয়া',
  ar:'العربية', fr:'Français',
}

export async function GET(req: NextRequest, { params }: { params: { slug: string[] } }) {
  try {
    const slug   = params.slug ?? []
    const pageKey = slug[0] ?? 'home'
    const locale  = slug[1] ?? 'en'

    const page = PAGE_DATA[pageKey] ?? PAGE_DATA.home
    const localeLabel = LOCALE_LABELS[locale] ?? 'English'

    // Class/subject specific
    let dynamicTitle = page.title
    let dynamicSub   = page.subtitle
    if (pageKey === 'class' && slug[2]) {
      dynamicTitle = `Class ${slug[2]} NCERT`
      dynamicSub   = slug[3]
        ? `${slug[3].charAt(0).toUpperCase() + slug[3].slice(1)} — Free AI Solutions`
        : 'All Subjects — Free AI Solutions'
    }

    return new ImageResponse(
      (
        <div
          style={{
            width:          '100%',
            height:         '100%',
            display:        'flex',
            flexDirection:  'column',
            background:     `linear-gradient(135deg, ${page.color}, ${page.color}dd)`,
            padding:        '60px',
            fontFamily:     'system-ui, sans-serif',
            position:       'relative',
          }}
        >
          {/* Background pattern */}
          <div style={{
            position:     'absolute', inset: 0,
            background:   'radial-gradient(circle at 80% 20%, rgba(255,255,255,0.08) 0%, transparent 60%)',
          }} />

          {/* Top: Logo + Locale */}
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'auto' }}>
            <div style={{ display:'flex', alignItems:'center', gap:'16px' }}>
              <div style={{
                width:'56px', height:'56px', borderRadius:'14px',
                background:'rgba(255,255,255,0.2)',
                display:'flex', alignItems:'center', justifyContent:'center',
                fontSize:'32px',
              }}>
                M
              </div>
              <div>
                <div style={{ color:'white', fontSize:'28px', fontWeight:'900', letterSpacing:'-0.5px' }}>MscTutor</div>
                <div style={{ color:'rgba(255,255,255,0.7)', fontSize:'14px' }}>Free AI Education</div>
              </div>
            </div>
            {locale !== 'en' && (
              <div style={{
                background:'rgba(255,255,255,0.2)', borderRadius:'999px',
                padding:'6px 18px', color:'white', fontSize:'16px', fontWeight:'700',
              }}>
                {localeLabel}
              </div>
            )}
          </div>

          {/* Main content */}
          <div style={{ display:'flex', flexDirection:'column', gap:'16px', marginTop:'40px' }}>
            <div style={{ fontSize:'80px' }}>{page.icon}</div>
            <div style={{ color:'white', fontSize:'58px', fontWeight:'900', lineHeight:'1.1', letterSpacing:'-1px' }}>
              {dynamicTitle}
            </div>
            <div style={{ color:'rgba(255,255,255,0.85)', fontSize:'28px', fontWeight:'500', lineHeight:'1.4' }}>
              {dynamicSub}
            </div>
          </div>

          {/* Bottom badges */}
          <div style={{ display:'flex', gap:'12px', marginTop:'40px' }}>
            {['100% Free', '12 Languages', 'Class 1-12', 'CBSE & ICSE'].map(badge => (
              <div key={badge} style={{
                background:'rgba(255,255,255,0.15)',
                border:'1px solid rgba(255,255,255,0.25)',
                borderRadius:'999px', padding:'8px 20px',
                color:'white', fontSize:'16px', fontWeight:'600',
              }}>
                {badge}
              </div>
            ))}
          </div>

          {/* URL watermark */}
          <div style={{
            position:'absolute', bottom:'40px', right:'60px',
            color:'rgba(255,255,255,0.5)', fontSize:'18px',
          }}>
            msctutor.in
          </div>
        </div>
      ),
      { width: 1200, height: 630 }
    )
  } catch {
    // Fallback: simple gradient with text
    return new ImageResponse(
      (
        <div style={{
          width:'100%', height:'100%', display:'flex', alignItems:'center',
          justifyContent:'center', background:'linear-gradient(135deg,#1a3a6b,#2563eb)',
          color:'white', fontSize:'48px', fontWeight:'900',
        }}>
          MscTutor — Free AI Education
        </div>
      ),
      { width: 1200, height: 630 }
    )
  }
}
